### ISSUE TITLE
Big issue

### ISSUE THREAD

**Issue by cry** [MarkSonn/Vuetify-Abstractified#2]
There’s javascript here 🤨

**Comment by MarkSonn** [comment]
Hi Cry,

I would like to begin but just making sure you're alright! Are you ok? There is no need to cry, even though I know how daunting real code is for new coders like yourself.

Thank you for raising this issue. I'm going to have to refer you to the following issue which might help you resolve the problem you are having. Please leave another comment if you require further hand-holding :)

Please refer to this issue: #1 

Kind regards,
Mark Sonnenschein
CEO, Pioneer and Visionary of Vuetify-Abstractified
